"""add approved_for_work field to WorkOrder

Revision ID: 1ca9b907a5a8
Revises: 8f4c2ca7e846
Create Date: 2025-07-09 08:04:42.901157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca9b907a5a8'
down_revision = '8f4c2ca7e846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_for_work', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('approved_for_work')

    # ### end Alembic commands ###
