"""Add is_approved to WorkOrderDocument

Revision ID: 23284a982986
Revises: 930b3c717c3b
Create Date: 2025-05-02 23:10:47.885402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23284a982986'
down_revision = '930b3c717c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
