"""Add progress_percent to ProjectTask

Revision ID: 3c944a15d355
Revises: ab5ed9a63e4e
Create Date: 2025-05-04 22:23:32.919985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c944a15d355'
down_revision = 'ab5ed9a63e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_column('progress_percent')

    # ### end Alembic commands ###
