"""Add project_id to WorkOrderDocument model

Revision ID: 7df282a7a6fe
Revises: d470e47be068
Create Date: 2025-05-04 17:22:12.609151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df282a7a6fe'
down_revision = 'd470e47be068'
branch_labels = None
depends_on = None


def upgrade():
    # Add project_id column first without the foreign key constraint
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
    
    # Then add the foreign key constraint with a name
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_work_order_document_project_id', 
            'project', 
            ['project_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
