"""Added document_type to WorkOrderDocument

Revision ID: 8f4c2ca7e846
Revises: 3c944a15d355
Create Date: 2025-05-08 07:34:38.766743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4c2ca7e846'
down_revision = '3c944a15d355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_document', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###
