"""Add classification to work orders

Revision ID: 930b3c717c3b
Revises: d4c09d0ebe7d
Create Date: 2025-04-30 08:33:26.408311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930b3c717c3b'
down_revision = 'd4c09d0ebe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('classification')

    # ### end Alembic commands ###
