"""empty message

Revision ID: ab5ed9a63e4e
Revises: 7df282a7a6fe
Create Date: 2025-05-04 21:47:26.437642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5ed9a63e4e'
down_revision = '7df282a7a6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
