"""add task_id to TimeEntry

Revision ID: d470e47be068
Revises: 58869c37c790
Create Date: 2025-05-04 13:58:57.446755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd470e47be068'
down_revision = '58869c37c790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_time_entry_task', 'project_task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_time_entry_task', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
